---
title: "TRIAGE Workflow"
author: "Jeff Brabec"
date: "8/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(here)
library(janitor)
library(gprofiler2)
library(magrittr)
library(igraph)
library(ranger)
library(kernlab)
library(baguette)
library(furrr)
library(R.utils)
library(parallel)
library(doParallel)
library(safejoin)
library(cluster)
library(fpc)

#Source in Functions
fun_dir <- list.files(here("src"), full.names = TRUE)

for(i in 1:length(fun_dir)) {
  
  source(fun_dir[i])
  
}
```

## Read in Data
```{r}
multi_net_kmeds_tibble <- read_csv(here("data/multi_net_kmeds_tibble.csv"))
```

## Split Data and Get Folds
```{r}
#Splitting Data
# set.seed(210)
# multi_net_initial_split <- initial_split(multi_net_kmeds_tibble, strata = class)
# multi_net_train <- training(multi_net_initial_split)
# multi_net_test <- testing(multi_net_initial_split)

set.seed(46)

multi_net_cv_folds <- nested_cv(multi_net_kmeds_tibble,
                                outside = vfold_cv(v = 2, strata = class),
                                inside = bootstraps(times = 3, strata = class))
```

## Set Hyper Parameters and Run Inner Models
```{r}
cost_vals = 10^seq(-5, 3, 1)
sigma_vals = 10^seq(-8, 0, 1)

dir.create(file.path(here("results"), paste("multi_net", "rbf", "results", sep = "_")))

res_dir <- here("results/multi_net_rbf_results")

plan(multisession)
multi_net_trial_results <- future_map2(multi_net_cv_folds$inner_resamples,
                                       multi_net_cv_folds$id,
                                       summarizing_results,
                                       res_dir = res_dir,
                                       learner = "svm_linear",
                                       cost = cost_vals,
                                       .options = furrr_options(seed = 42)) 

```
## Aggregate Model Performance Across Hyper-Parameters
```{r}
multi_net_fold_res <- map(multi_net_trial_results, format_folds)

multi_net_score_res <- map(multi_net_fold_res, median_wrapper)

best_hypers <- function(dat) dat[which.max(dat$auc),]

best_multi_net_hyper_df <- map_dfr(multi_net_score_res, best_hypers) %>% 
  mutate(fold_id = multi_net_cv_folds$id) 
```

```{r}
param_list <- list(cost = best_multi_net_hyper_df$cost,
                   fold_id = best_multi_net_hyper_df$fold_id)

best_multi_net_models <- best_multi_net_hyper_df %>% 
  mutate(models =  future_pmap(param_list, 
                               pick_model,
                               learner = "svm_linear",
                               results_dir = here("results/multi_net_linear_results"))) %>% 
  mutate(splits = multi_net_cv_folds$splits)
```

```{r}
dir.create(file.path(here("results"), paste("multi_net", "linear", "final", "predictions", sep = "_")))

best_multi_net_mod_list <- list(splits = best_multi_net_models$splits,
                                models = best_multi_net_models$models,
                                fold_id = best_multi_net_models$fold_id)

final_res_dir <- here("results/multi_net_linear_final_predictions")

final_multi_net_auc <- best_multi_net_models %>% 
  mutate(assessment_auc = pmap_dbl(best_multi_net_mod_list, 
                                   bag_wrapper,
                                   res_dir = final_res_dir)) %>% 
  select(cost, fold_id, auc, assessment_auc)
```

## Full test final AUCs
```{r}
final_multi_net_auc <- read_rds(here("results/final_multi_net_auc.rds"))

final_multi_net_auc %>% 
  ggplot(aes(x = auc, y = assessment_auc, color = cost)) +
  geom_point() +
  geom_smooth(method = "lm")
```

